# Generated by Django 3.2.9 on 2022-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211229_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(default='yoy', max_length=200, null=True),
        ),
    ]
